---
- name: Deploy Flask App
  hosts: all
  become: yes

  tasks:
    - name: Add the default Ubuntu repository
      apt_repository:
        repo: 'deb http://archive.ubuntu.com/ubuntu focal main'
        state: present

    - name: Install required packages
      package:
        name:
          - python3
          - python3-pip
          - git

    - name: Create the destination folder
      file:
        path: home/ubuntu/flask-app
        state: directory

    - name: Copy Flask application code
      copy:
        src: project.py
        dest: /home/ubuntu/flask-app

    - name: Clone the repository
      git:
        repo: https://github.com/ADENIKE2010/midterm-project.git
        dest: /opt/flask-app

    - name: Install firewall package
      package:
        name: firewalld
        state: latest

    - name: Start firewall service
      service:
        name: firewalld
        state: started

    - name: Add firewall rule for Flask application
      shell: firewall-cmd --zone=public --add-port=5000/tcp --permanent

    - name: Reload firewall configuration
      shell: firewall-cmd --reload


    - name: Install Flask and its dependencies
      pip:
        name: flask
        chdir: /opt/flask-app

    - name: Start the Flask App
      command: python3 /opt/flask-app/app.py
      async: 1
      poll: 0
...
